version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db_prod
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: redis_prod
    restart: always
    volumes:
      - redis_data_prod:/data

  app:
    image: ${DOCKER_HUB_USERNAME}/pythonproject5:${IMAGE_TAG}
    container_name: app_prod
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    build: ./nginx
    container_name: nginx_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume_prod:/vol/web/static
      - media_volume_prod:/vol/web/media
    depends_on:
      - app

  celery:
    image: ${DOCKER_HUB_USERNAME}/pythonproject5:${IMAGE_TAG}
    container_name: celery_prod
    restart: always
    command: python run_worker.py worker -l info
    env_file:
      - .env
    depends_on:
      - app

  celery_beat:
    image: ${DOCKER_HUB_USERNAME}/pythonproject5:${IMAGE_TAG}
    container_name: celery_beat_prod
    restart: always
    command: python run_worker.py beat -l info
    env_file:
      - .env
    depends_on:
      - app

volumes:
  pg_data_prod:
  redis_data_prod:
  static_volume_prod:
  media_volume_prod: