# Generated by Django 5.2.6 on 2025-09-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=10000, verbose_name="Цена"),
        ),
    ]
