# Generated by Django 5.2.6 on 2025-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
